//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("SA")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © 2023 Sergey A Kryukov")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Generic State Machine Engine based on enumeration type parameter")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.1.0.0 ")]
[assembly: System.Reflection.AssemblyProductAttribute("State Machine Engine")]
[assembly: System.Reflection.AssemblyTitleAttribute("State Machine Engine Demo")]
[assembly: System.Reflection.AssemblyVersionAttribute("0.1.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

